version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/todo.sql"
    schema: "schema/migrations/000001_create_todo_items.up.sql"
    gen:
      go:
        package: "db"
        out: "."
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        json_tags_case_style: "camel"
        sql_package: "pgx/v5"